[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[build.nixpacksPlan.phases.install]
cmds = ["pip install -r requirements.txt"]

[deploy]
startCommand = "python -m gunicorn app:app --bind 0.0.0.0:$PORT"
